### ISSUE TITLE
KPI - Dash Board Creation 

### ISSUE THREAD

**Issue by jeremiah-carlson** [HMF-Dev/IssueTracking#3]
#### Desired Outcome
The goal of this project is to establish a base model dash board for specific key performance metrics. This will give specific visibility on key areas of focus and improvement for HMF Express. 

#### Implementation
This plan will be implemented using dedicated TV monitors at each satellite location. These monitors will need access to static html files to be programmatically  updated periodically. 

#### 🔑  Metrics
- TBA

#### Tasks
- [x] Build HTML index
- [x] Add Media
- [x] Design Data Agg
- [x] Design Report Builder
- [x] Map Report Paths
- [x] Test

#### Root Directory
[kpi_dash](https://github.com/HMF-Dev/kpi_dash)

**Comment by jeremiah-carlson** [comment]
#### Build HTML index / Add Media
The base html was designed using bootstrap and an external style sheet. Also added was a js file for table data and a js script for table loading. The only media add is the Senneca logo which is linked via the web.

#### Next Steps
Data for this dashboard will be aggregated and processed by python. It needs to be separated into 2 categories, and then sent to the individual source computers. 
 - data.js (table data)
 - graph.svg (via matplotlib)

**Comment by jeremiah-carlson** [comment]
## Alter Graphing Method
Python graphing with matplotlib has been replaced with chart.js in order to increase maintainability of the code base. This change allows for graphs to be generated with the data that must already be transferred for use in the data tables. This significantly reduces the applications python dependency and allows for future portability via api integration. 

#### Sample (Transparent Background)
![image](https://user-images.githubusercontent.com/87202597/183089522-0f4d2b4e-1e9a-4bd5-b92b-af2da0118529.png)

#### Packages
- [chart.js](https://github.com/chartjs/Chart.js#documentation)
- [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels#overview)

#### Files
- [data.js](https://github.com/HMF-Dev/kpi_dash/blob/37c78652d49715487c4d4abcb0a27396265dce11/scripts/data.js) -- template
- [app.js](https://github.com/HMF-Dev/kpi_dash/blob/98fc5fede40866baf7bdc8544ddf12ba98edc46d/scripts/app.js) -- as of 8/1/22

**Comment by jeremiah-carlson** [comment]
## Data Agg
#### Separation of Responsibilities 
This project require multiple computational units. In this case that will manifest as 7 clients and a host. For this reason this application has been split into two repositories [kpi_dash](https://github.com/HMF-Dev/kpi_dash) for client side code and [kpi_dash_server](https://github.com/HMF-Dev/kpi_dash_server) for the host. 

#### Data Sources
- MSSQL Server (Main)
- Excel (Metrics Report)

#### Query Methods
The SQL Server has been queried with standard methods using [pyodbc](https://github.com/mkleehammer/pyodbc). The excel file has been mapped to a dictionary object to allow records to be called as a combination of factors which each map to a distinct row index. These record are then collected using [openpyxl](https://openpyxl.readthedocs.io/en/stable/).

#### Output Format
Once records are collected they are then applied to an `%s` string to build `data.js ` this file defines each set of records as a specific JavaScript-Object assigned variable. This file is referenced in the `index.html` file and the concerned variables are loaded in prior to `app.js` and `loadTableData.js`.
